function [results, run_info] = validate_fig3_sca_original(varargin)
if nargin == 1 && isstruct(varargin{1})
    run_cfg = pinching.experiments.build_run_config(varargin{1});
else
    run_cfg = pinching.experiments.build_run_config(varargin{:});
end

fig3_cfg = build_fig3_config(run_cfg);
[results, run_info] = pinching.api.run_validation(fig3_cfg);
[results, run_info] = wrap_fig3_outputs(results, run_info, fig3_cfg, run_cfg);
end

function fig3_cfg = build_fig3_config(run_cfg)
% Fig. 3 keeps its own default settings here so the validation entry point
% itself remains the first place to edit sweep ranges and plotting choices.
settings = default_fig3_settings();

params = pinching.model.default_params();
params = pinching.experiments.apply_param_overrides(params, run_cfg.param_overrides);

fig3_cfg = struct();
fig3_cfg.name = settings.name;
fig3_cfg.result_name = settings.result_name;
fig3_cfg.figure_name = settings.figure_name;
fig3_cfg.output_tag = fullfile(run_cfg.output_tag, 'fig3');
fig3_cfg.output_root = run_cfg.results_root;
fig3_cfg.plot_title = settings.plot_title;
fig3_cfg.x_label = settings.x_label;
fig3_cfg.y_label = settings.y_label;

% Fig. 3 is a transmit-power sweep. Edit settings.power_grid in
% default_fig3_settings() for the in-file default, or pass fig3_power_grid
% at call time to override it from the outside.
fig3_cfg.sweep_param = settings.sweep_param;
fig3_cfg.sweep_values = resolve_fig3_power_grid(run_cfg, settings);

% The comparison curves shown on the figure.
fig3_cfg.methods = settings.methods;

% Random realizations are generated by the shared runner from params.mc_trials.
fig3_cfg.params = params;
fig3_cfg.scenario_mode = settings.scenario_mode;
fig3_cfg.sca_opts = run_cfg.sca_opts;
fig3_cfg.verbose = run_cfg.verbose;
end

function settings = default_fig3_settings()
settings = struct();
settings.name = 'Fig. 3 Validation';
settings.result_name = 'fig3_sca_original';
settings.figure_name = 'fig3_sca_original_comparison';
settings.plot_title = 'Fig. 3 Validation';
settings.x_label = 'Transmit Power Budget [W]';
settings.y_label = 'Communication Rate [bit/s/Hz]';
settings.sweep_param = 'Pmax';
settings.power_grid = 4:2:16;
settings.methods = {'sca', 'target_oriented', 'midpoint', 'user_centric', 'conventional'};
settings.scenario_mode = 'random_realizations';
end

function power_grid = resolve_fig3_power_grid(run_cfg, settings)
default_run_cfg = pinching.experiments.default_run_config();

% If the caller explicitly changed fig3_power_grid/power_grid, respect it.
% Otherwise, keep Fig. 3's own local default from this file.
if isequal(run_cfg.fig3.power_grid, default_run_cfg.fig3.power_grid)
    power_grid = settings.power_grid;
else
    power_grid = run_cfg.fig3.power_grid;
end
end

function [results, run_info] = wrap_fig3_outputs(results, run_info, fig3_cfg, run_cfg)
results.figure_id = 3;
results.figure_key = 'fig3';
results.figure_config = struct( ...
    'sweep_param', fig3_cfg.sweep_param, ...
    'sweep_values', fig3_cfg.sweep_values, ...
    'methods', {fig3_cfg.methods}, ...
    'scenario_mode', fig3_cfg.scenario_mode, ...
    'params', fig3_cfg.params, ...
    'sca_opts', fig3_cfg.sca_opts);
results.run_config = run_cfg;

run_info.figure_id = 3;
run_info.figure_key = 'fig3';
end
